// ============================================================
// DATA.JS — All static game definitions
// ============================================================

const ROOMS = {
  bedroom: {
    id: 'bedroom',
    name: 'Yataq otağı',
    icon: '🛏',
    desc: 'Əsas istirahət yeri. Hər gün can bərpa edir.',
    built: true,      // starts built
    locked: false,
    cost: {},
    effect: { healthRegen: 5 },
    canBuildIn: [],
    gridX: 0, gridY: 0, gridW: 2, gridH: 2,
  },
  workbench: {
    id: 'workbench',
    name: 'Craft masası',
    icon: '🔧',
    desc: 'Əşyalar düzəltmək üçün. Craft menyu açılır.',
    built: true,
    locked: false,
    cost: {},
    effect: { unlockCraft: true },
    gridX: 2, gridY: 0, gridW: 1, gridH: 1,
  },
  waterCollector: {
    id: 'waterCollector',
    name: 'Su toplayıcı',
    icon: '💧',
    desc: 'Hər gün 2 su toplayır.',
    built: false,
    locked: false,
    cost: { wood: 3, scrap: 2 },
    effect: { waterPerDay: 2 },
    gridX: 2, gridY: 1, gridW: 1, gridH: 1,
  },
  garden: {
    id: 'garden',
    name: 'Bağça',
    icon: '🌱',
    desc: 'Hər 2 gündə yemək verir.',
    built: false,
    locked: false,
    cost: { wood: 4, cloth: 2 },
    effect: { foodPerTwoDays: 2 },
    gridX: 0, gridY: 2, gridW: 1, gridH: 1,
  },
  weaponRack: {
    id: 'weaponRack',
    name: 'Silah rəfi',
    icon: '⚔',
    desc: 'Silahları saxla, artı bonus damage.',
    built: false,
    locked: false,
    cost: { wood: 2, scrap: 4 },
    effect: { damagBonus: 2 },
    gridX: 1, gridY: 2, gridW: 1, gridH: 1,
  },
  medStation: {
    id: 'medStation',
    name: 'Tibb köşəsi',
    icon: '🩺',
    desc: 'Hər gün +3 can, sarğı craft.',
    built: false,
    locked: false,
    cost: { cloth: 5, scrap: 3 },
    effect: { healthRegen: 3, unlockMedCraft: true },
    gridX: 2, gridY: 2, gridW: 1, gridH: 1,
  },
  storageRoom: {
    id: 'storageRoom',
    name: 'Anbar',
    icon: '📦',
    desc: 'Çanta tutumunu 10 kq artırır.',
    built: false,
    locked: false,
    cost: { wood: 5, scrap: 2 },
    effect: { carryBonus: 10 },
    gridX: 0, gridY: 3, gridW: 2, gridH: 1,
  },
  radioRoom: {
    id: 'radioRoom',
    name: 'Radio otağı',
    icon: '📻',
    desc: 'Xəritədə gizli lokasiyalar açılır.',
    built: false,
    locked: false,
    cost: { scrap: 8, battery: 2 },
    effect: { unlockHiddenLocations: true },
    gridX: 2, gridY: 3, gridW: 1, gridH: 1,
  },
};

const ITEMS = {
  // Resources
  wood:        { id: 'wood',      name: 'Taxta',      icon: '🪵', weight: 1,   type: 'resource' },
  scrap:       { id: 'scrap',     name: 'Skrap',      icon: '⚙',  weight: 0.5, type: 'resource' },
  cloth:       { id: 'cloth',     name: 'Parça',      icon: '🧶',  weight: 0.3, type: 'resource' },
  battery:     { id: 'battery',   name: 'Batareya',   icon: '🔋',  weight: 0.5, type: 'resource' },
  food:        { id: 'food',      name: 'Konserv',    icon: '🥫',  weight: 0.4, type: 'consumable', hunger: 25 },
  water:       { id: 'water',     name: 'Su',         icon: '💧',  weight: 0.5, type: 'consumable', thirst: 30 },
  medkit:      { id: 'medkit',    name: 'Dərman',     icon: '💊',  weight: 0.3, type: 'consumable', health: 30 },
  bandage:     { id: 'bandage',   name: 'Sarğı',      icon: '🩹',  weight: 0.2, type: 'consumable', health: 15 },
  // Weapons
  knife:       { id: 'knife',     name: 'Bıçaq',      icon: '🔪',  weight: 0.5, type: 'weapon', damage: [4,8],  hit: 90, range: 'melee' },
  pipe:        { id: 'pipe',      name: 'Boru',       icon: '🔩',  weight: 1.5, type: 'weapon', damage: [6,10], hit: 80, range: 'melee' },
  axe:         { id: 'axe',       name: 'Balta',      icon: '🪓',  weight: 2,   type: 'weapon', damage: [9,14], hit: 75, range: 'melee' },
  pistol:      { id: 'pistol',    name: 'Tapança',    icon: '🔫',  weight: 1,   type: 'weapon', damage: [12,18],hit: 85, range: 'ranged', ammoType: 'ammo9mm' },
  ammo9mm:     { id: 'ammo9mm',   name: '9mm x12',    icon: '🟡',  weight: 0.3, type: 'ammo', count: 12 },
  // Armor
  jacket:      { id: 'jacket',    name: 'Gödəkcə',    icon: '🧥',  weight: 2,   type: 'armor', defense: 3 },
};

const RECIPES = [
  { id: 'bandage',   name: 'Sarğı',        icon: '🩹',  result: 'bandage',  qty: 2, cost: { cloth: 2 },             requires: null },
  { id: 'torch',     name: 'Məşəl',        icon: '🔦',  result: 'torch',    qty: 1, cost: { wood: 1, cloth: 1 },    requires: null },
  { id: 'pipe_wpn',  name: 'Boru (silah)', icon: '🔩',  result: 'pipe',     qty: 1, cost: { scrap: 3 },             requires: 'workbench' },
  { id: 'molotov',   name: 'Molotov',      icon: '🍾',  result: 'molotov',  qty: 1, cost: { cloth: 2, battery: 1 }, requires: 'workbench' },
];

const ENEMIES = {
  walker: {
    id: 'walker',
    name: 'Yürüyən',
    icon: '🧟',
    maxHp: 20,
    damage: [3, 6],
    hit: 70,
    xp: 10,
    loot: { scrap: [0,1], cloth: [0,1] },
  },
  runner: {
    id: 'runner',
    name: 'Qaçan',
    icon: '🧟',
    maxHp: 14,
    damage: [5, 9],
    hit: 85,
    xp: 15,
    loot: { food: [0,1] },
  },
  bloater: {
    id: 'bloater',
    name: 'Şişman',
    icon: '🧟',
    maxHp: 45,
    damage: [8, 14],
    hit: 60,
    xp: 25,
    loot: { scrap: [1,3] },
  },
  armored: {
    id: 'armored',
    name: 'Zırhlı',
    icon: '🧟',
    maxHp: 35,
    damage: [6, 10],
    hit: 75,
    defense: 4,
    xp: 30,
    loot: { scrap: [2,4] },
  },
};

const LOCATIONS = [
  {
    id: 'supermarket',
    name: 'Supermarket',
    icon: '🏪',
    desc: 'Yaxınlıqdakı tərk edilmiş market. Yemək var.',
    x: 0.28, y: 0.18,    // relative canvas position
    distanceKm: 1.2,
    travelHours: 0.5,
    danger: 2,           // 1-5
    rooms: [
      { name: 'Giriş',       enemies: ['walker'],           loot: ['cloth', 'scrap'] },
      { name: 'Rəflər A',    enemies: ['walker', 'walker'], loot: ['food', 'food', 'water'] },
      { name: 'Rəflər B',    enemies: [],                   loot: ['food', 'food', 'food'] },
      { name: 'Anbar',       enemies: ['runner'],           loot: ['food', 'medkit', 'wood'] },
    ],
  },
  {
    id: 'hospital',
    name: 'Xəstəxana',
    icon: '🏥',
    desc: 'Tibb ləvazimatları. Çox təhlükəli.',
    x: 0.72, y: 0.12,
    distanceKm: 3.5,
    travelHours: 1.5,
    danger: 4,
    rooms: [
      { name: 'Qəbul',        enemies: ['walker', 'runner'],           loot: ['bandage'] },
      { name: 'Dəhliz',       enemies: ['walker', 'walker', 'runner'], loot: ['cloth'] },
      { name: 'Aptek',        enemies: [],                             loot: ['medkit', 'medkit', 'bandage'] },
      { name: 'Cərrahiyyə',   enemies: ['armored'],                    loot: ['medkit', 'cloth', 'cloth'] },
      { name: 'Anbar ↓',      enemies: ['bloater'],                    loot: ['medkit', 'battery', 'scrap'] },
    ],
  },
  {
    id: 'police',
    name: 'Polis',
    icon: '🏛',
    desc: 'Silah və sursat. Möhkəm qapılar.',
    x: 0.52, y: 0.42,
    distanceKm: 2.8,
    travelHours: 1.2,
    danger: 5,
    rooms: [
      { name: 'Giriş',        enemies: ['walker', 'walker'],            loot: ['scrap'] },
      { name: 'Koridor',      enemies: ['runner', 'armored'],           loot: ['cloth', 'scrap'] },
      { name: 'Ofis',         enemies: ['walker'],                      loot: ['battery', 'food'] },
      { name: 'Silah anbarı', enemies: ['armored', 'armored'],          loot: ['ammo9mm', 'ammo9mm', 'pistol'] },
    ],
  },
  {
    id: 'school',
    name: 'Məktəb',
    icon: '🏫',
    desc: 'Böyük bina. Çox loot, çox zombi.',
    x: 0.18, y: 0.55,
    distanceKm: 4.0,
    travelHours: 1.8,
    danger: 3,
    rooms: [
      { name: 'Həyət',          enemies: ['walker'],                      loot: ['wood', 'scrap'] },
      { name: 'Sinif 1',        enemies: ['walker', 'walker'],            loot: ['cloth', 'wood'] },
      { name: 'Sinif 2',        enemies: ['runner'],                      loot: ['food', 'food'] },
      { name: 'Laboratoriya',   enemies: [],                              loot: ['battery', 'scrap', 'cloth'] },
      { name: 'Yemək zalı',     enemies: ['bloater'],                     loot: ['food', 'food', 'food'] },
      { name: 'İnzibati',       enemies: ['walker', 'armored'],           loot: ['scrap', 'wood'] },
      { name: 'Çardaq 🔒',      enemies: ['armored', 'armored', 'runner'],loot: ['pistol', 'ammo9mm', 'medkit'] },
    ],
  },
  {
    id: 'gas_station',
    name: 'Yanacaq məntəqəsi',
    icon: '⛽',
    desc: 'Yaxın, sürətli. Az loot.',
    x: 0.82, y: 0.62,
    distanceKm: 0.8,
    travelHours: 0.3,
    danger: 1,
    rooms: [
      { name: 'Mağaza',   enemies: ['walker'],  loot: ['food', 'battery'] },
      { name: 'Qaraj',    enemies: [],          loot: ['scrap', 'scrap', 'wood'] },
    ],
  },
];
